import { createContext, useContext, useState, useEffect } from "react";

export type Language = "en" | "es" | "ar";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    // Header
    "header.title": "Aptexa ToolHub",
    "header.subtitle": "Professional Online Tools",
    "header.search": "Search tools...",
    "header.dashboard": "Dashboard",
    "header.favorites": "Favorites",
    "header.recent": "Recent",
    
    // Dashboard
    "dashboard.title": "Professional Online Tools",
    "dashboard.description": "Access powerful tools to enhance your productivity and streamline your workflow",
    "dashboard.hero.title": "Professional Online Tools",
    "dashboard.hero.description": "Access powerful tools to enhance your productivity and streamline your workflow - from {barcodes} and {pdfs} to {signatures} and {development} utilities.",
    "dashboard.hero.barcodes": "barcode generation",
    "dashboard.hero.pdfs": "PDF processing",
    "dashboard.hero.signatures": "digital signatures",
    "dashboard.hero.development": "development tools",
    "dashboard.stats.tools": "Total Tools",
    "dashboard.stats.categories": "Categories",
    "dashboard.stats.popular": "Most Popular",
    "dashboard.stats.popularTool": "PDF Tools",
    "dashboard.stats.free": "Free to Use",
    "dashboard.quickAccess": "Quick Access",
    "dashboard.allCategories": "All Tool Categories",
    "dashboard.popularTools": "Popular Tools",
    "dashboard.quickActions": "Quick Actions",
    "dashboard.recentlyUsed": "Recently Used",
    "dashboard.features.title": "Why Choose Aptexa's ToolHub?",
    "dashboard.features.secure": "Secure & Private",
    "dashboard.features.secureDesc": "All processing happens in your browser. Your data never leaves your device.",
    "dashboard.features.fast": "Lightning Fast",
    "dashboard.features.fastDesc": "Optimized tools that work instantly without server delays.",
    "dashboard.features.mobile": "Mobile Friendly",
    "dashboard.features.mobileDesc": "Works perfectly on all devices, from desktop to mobile.",
    
    // Categories
    "category.barcodes.title": "Barcode & QR Tools",
    "category.barcodes.description": "Generate and scan various barcode formats",
    "category.pdf-tools.title": "PDF Tools",
    "category.pdf-tools.description": "Convert, merge, split, compress and manipulate PDF documents",
    "category.image-tools.title": "Image Tools",
    "category.image-tools.description": "Resize, compress, convert and edit images in various formats",
    "category.text-tools.title": "Text & Content Tools",
    "category.text-tools.description": "Format, analyze and manipulate text content and code",
    "category.converters.title": "Converter Tools",
    "category.converters.description": "Convert units, currencies, colors and file formats",
    "category.generators.title": "Generator Tools",
    "category.generators.description": "Generate passwords, signatures, invoices and CSS gradients",
    "category.developer-tools.title": "Developer Tools",
    "category.developer-tools.description": "Debug, test and optimize code with professional developer utilities",
    
    // Barcode Generator
    "barcodeGenerator.title": "Barcode & QR Code Generator",
    "barcodeGenerator.subtitle": "Generate 85+ barcode types including QR codes, linear barcodes, postal codes, business cards, Wi-Fi, events, and specialty formats",
    "barcodeGenerator.barcodeType": "Barcode Type",
    "barcodeGenerator.available": "available",
    "barcodeGenerator.searchTypes": "Search barcode types...",
    "barcodeGenerator.allCategories": "All Categories",
    "barcodeGenerator.selectType": "Select a barcode type...",
    "barcodeGenerator.noTypesFound": "No barcode types found matching your search",
    "barcodeGenerator.professional": "Professional",
    "barcodeGenerator.dataToEncode": "Data to Encode",
    "barcodeGenerator.useSampleData": "Use Sample Data",
    "barcodeGenerator.scaleLabel": "Scale",
    "barcodeGenerator.heightLabel": "Height",
    "barcodeGenerator.includeText": "Include Text",
    "barcodeGenerator.textSize": "Text Size",
    "barcodeGenerator.backgroundColor": "Background Color",
    "barcodeGenerator.generate": "Generate Barcode",
    "barcodeGenerator.generating": "Generating...",
    "barcodeGenerator.generatedBarcode": "Generated Barcode",
    "barcodeGenerator.copy": "Copy",
    "barcodeGenerator.barcodeWillAppear": "Your barcode will appear here",
    "barcodeGenerator.professionalGrade": "Professional Grade",
    "barcodeGenerator.enterData": "Enter your data here...",
    "barcodeGenerator.sampleDataLoaded": "Sample Data Loaded",
    "barcodeGenerator.sampleDataDesc": "Sample data has been loaded for this barcode type",
    "barcodeGenerator.barcodeGenerated": "Barcode Generated",
    "barcodeGenerator.barcodeGeneratedDesc": "Your authentic, scannable barcode has been generated!",
    "barcodeGenerator.generationFailed": "Generation Failed",
    "barcodeGenerator.invalidInput": "Invalid Input",
    "barcodeGenerator.selectTypeAndEnter": "Please select a barcode type and enter data",
    "barcodeGenerator.copiedClipboard": "Copied to Clipboard",
    "barcodeGenerator.copiedClipboardDesc": "Barcode image copied to clipboard",
    "barcodeGenerator.copyFailed": "Copy Failed",
    "barcodeGenerator.copyFailedDesc": "Unable to copy to clipboard",
    "barcodeGenerator.svgFeature": "SVG Feature",
    "barcodeGenerator.svgFeatureDesc": "SVG download will be implemented in the next update. PNG download is fully functional.",

    // Barcode Categories
    "barcode.linearCodes": "Linear Codes",
    "barcode.postalCodes": "Postal Codes", 
    "barcode.gs1DataBar": "GS1 DataBar",
    "barcode.eanUpc": "EAN / UPC",
    "barcode.twoDCodes": "2D Codes",
    "barcode.gs1TwoDCodes": "GS1 2D Barcodes",
    "barcode.bankingPayment": "Banking and Payments",
    "barcode.mobileTags": "Mobile Tagging",
    "barcode.healthcare": "Healthcare Codes",
    "barcode.businessCards": "Business Cards",
    "barcode.events": "Event Barcodes",
    "barcode.wifi": "Wi-Fi Barcodes",
    "barcode.isbn": "ISBN Codes",

    // Barcode Type Names
    "Code-128": "Code-128",
    "Code-11": "Code-11",
    "Code 2 of 5": "Code 2 of 5",
    "Code-39": "Code-39",
    "Code-39 Full ASCII": "Code-39 Full ASCII",
    "Code-93": "Code-93",
    "GS1-128": "GS1-128",
    "MSI": "MSI",
    "Pharmacode": "Pharmacode",
    "Pharmacode Two-Track": "Pharmacode Two-Track",
    "Telepen": "Telepen",
    "Australian Post": "Australian Post",
    "Deutsche Post Identcode": "Deutsche Post Identcode",
    "DPD Code": "DPD Code",
    "Japan Post": "Japan Post",
    "Royal Mail 4-State": "Royal Mail 4-State",
    "USPS POSTNET": "USPS POSTNET",
    "USPS Intelligent Mail": "USPS Intelligent Mail",
    "GS1 DataBar Omnidirectional": "GS1 DataBar Omnidirectional",
    "GS1 DataBar Stacked": "GS1 DataBar Stacked",
    "GS1 DataBar Limited": "GS1 DataBar Limited",
    "GS1 DataBar Expanded": "GS1 DataBar Expanded",
    "GS1 DataBar Expanded Stacked": "GS1 DataBar Expanded Stacked",
    "EAN-8": "EAN-8",
    "EAN-13": "EAN-13",
    "UPC-A": "UPC-A",
    "UPC-E": "UPC-E",
    "Data Matrix": "Data Matrix",
    "QR Code": "QR Code",
    "PDF417": "PDF417",
    "MicroPDF417": "MicroPDF417",
    "Aztec Code": "Aztec Code",
    "MaxiCode": "MaxiCode",

    // Currency Converter
    "currencyConverter.title": "Real-Time Currency Converter",
    "currencyConverter.lastUpdated": "Last Updated",
    "currencyConverter.refresh": "Refresh",
    "currencyConverter.from": "From",
    "currencyConverter.to": "To",
    "currencyConverter.enterAmount": "Enter amount",
    "currencyConverter.convertedAmount": "Converted Amount",
    "currencyConverter.convertCurrency": "Convert Currency",
    "currencyConverter.converting": "Converting...",
    "currencyConverter.clear": "Clear",
    "currencyConverter.liveExchangeRates": "Live Exchange Rates",
    "currencyConverter.autoRefresh": "Auto Refresh",
    "currencyConverter.realTimeData": "Real-time currency data updated hourly from financial markets",
    "currencyConverter.intelligentCaching": "Auto-refreshing rates with intelligent caching",

    // PDF Tools
    "pdfMerger.title": "PDF Merger",
    "pdfMerger.subtitle": "Combine multiple PDF files into a single document",
    "pdfMerger.uploadFiles": "Upload PDF Files",
    "pdfMerger.chooseFiles": "Choose Files",
    "pdfMerger.dragDrop": "Drag and drop PDF files here, or click to browse",
    "pdfMerger.fileTypes": "PDF files only",
    "pdfMerger.mergeFiles": "Merge Files",
    "pdfMerger.merging": "Merging...",
    "pdfMerger.downloadMerged": "Download Merged PDF",
    "pdfMerger.mergingComplete": "Merging Complete!",
    "pdfMerger.readyForDownload": "Your merged PDF file is ready for download",
    "pdfMerger.reset": "Reset",
    "pdfMerger.removeFile": "Remove",
    "pdfMerger.fileSelected": "file selected",
    "pdfMerger.filesSelected": "files selected",
    "pdfMerger.success": "PDF merged successfully!",

    "pdfSplitter.title": "PDF Splitter",
    "pdfSplitter.subtitle": "Extract specific pages or ranges from PDF documents",
    "pdfSplitter.uploadFile": "Upload PDF File",
    "pdfSplitter.chooseFile": "Choose File",
    "pdfSplitter.dragDrop": "Drag and drop PDF file here, or click to browse",
    "pdfSplitter.specificPages": "Specific Pages",
    "pdfSplitter.pageRanges": "Page Ranges",
    "pdfSplitter.everyNPages": "Every N Pages",
    "pdfSplitter.fixedSizeChunks": "Fixed Size Chunks",
    "pdfSplitter.splitPdf": "Split PDF",
    "pdfSplitter.splitting": "Splitting...",
    "pdfSplitter.inputRequired": "Input Required",
    "pdfSplitter.specifyPagesOrRanges": "Please specify pages or ranges to extract",
    "pdfSplitter.error": "Error",
    "pdfSplitter.failedToSplit": "Failed to split PDF",
    "pdfSplitter.downloadAll": "Download All",
    "pdfSplitter.reset": "Reset",
    "pdfSplitter.extractedPages": "Extracted Pages",
    "pdfSplitter.page": "Page",
    "pdfSplitter.download": "Download",
    "pdfSplitter.splitSuccessful": "Split Successful!",
    "pdfSplitter.extractedPagesCount": "pages extracted successfully",

    "pdfConverter.title": "PDF Converter",
    "pdfConverter.subtitle": "Convert PDFs to various formats and vice versa",
    "pdfConverter.uploadFile": "Upload File",
    "pdfConverter.chooseFile": "Choose File",
    "pdfConverter.dragDrop": "Drag and drop file here, or click to browse",
    "pdfConverter.convertFile": "Convert File",
    "pdfConverter.converting": "Converting...",
    "pdfConverter.conversionComplete": "Conversion Complete!",
    "pdfConverter.readyForDownload": "Ready for Download",
    "pdfConverter.selectOutputFormat": "Select Output Format",
    "pdfConverter.chooseConversionFormat": "Choose Conversion Format",
    "pdfConverter.supportedFormats": "Supported formats: PDF, Word (DOC/DOCX), Excel (XLS/XLSX), Images (JPG/PNG/GIF/BMP)",

    // Text Tools
    "caseConverter.title": "Case Converter",
    "caseConverter.inputText": "Input Text",
    "caseConverter.enterText": "Enter your text here...",
    "caseConverter.conversionType": "Conversion Type",
    "caseConverter.uppercase": "UPPERCASE",
    "caseConverter.lowercase": "lowercase",
    "caseConverter.titleCase": "Title Case",
    "caseConverter.sentenceCase": "Sentence case",
    "caseConverter.camelCase": "camelCase",
    "caseConverter.pascalCase": "PascalCase",
    "caseConverter.snakeCase": "snake_case",
    "caseConverter.kebabCase": "kebab-case",
    "caseConverter.convertCase": "Convert Case",
    "caseConverter.converting": "Converting...",
    "caseConverter.outputText": "Output Text",
    "caseConverter.copy": "Copy",

    "textReverser.title": "Text Reverser",
    "textReverser.inputText": "Input Text",
    "textReverser.enterText": "Enter your text here...",
    "textReverser.reverseText": "Reverse Text",
    "textReverser.reversing": "Reversing...",
    "textReverser.reversedText": "Reversed Text",
    "textReverser.copy": "Copy",

    "loremGenerator.title": "Lorem Ipsum Generator",
    "loremGenerator.type": "Type",
    "loremGenerator.count": "Count",
    "loremGenerator.paragraphs": "Paragraphs",
    "loremGenerator.sentences": "Sentences",
    "loremGenerator.words": "Words",
    "loremGenerator.generateLorem": "Generate Lorem",
    "loremGenerator.generating": "Generating...",
    "loremGenerator.generatedText": "Generated Text",
    "loremGenerator.copy": "Copy",

    "textSlug.title": "Text to Slug Converter",
    "textSlug.inputText": "Input Text",
    "textSlug.enterText": "Enter your text here...",
    "textSlug.generateSlug": "Generate Slug",
    "textSlug.generatedSlug": "Generated Slug",
    "textSlug.copy": "Copy",

    "wordCounter.title": "Word Counter",
    "wordCounter.inputText": "Input Text",
    "wordCounter.enterText": "Enter or paste your text here...",
    "wordCounter.statistics": "Statistics",
    "wordCounter.characters": "Characters",
    "wordCounter.charactersNoSpaces": "Characters (no spaces)",
    "wordCounter.words": "Words",
    "wordCounter.sentences": "Sentences",
    "wordCounter.paragraphs": "Paragraphs",
    "wordCounter.readingTime": "Reading Time",
    "wordCounter.minutes": "minutes",

    // Developer Tools
    "hashGenerator.title": "Hash Generator",
    "hashGenerator.inputText": "Input Text",
    "hashGenerator.enterText": "Enter your text here...",
    "hashGenerator.hashType": "Hash Type",
    "hashGenerator.generateHash": "Generate Hash",
    "hashGenerator.generating": "Generating...",
    "hashGenerator.outputHash": "Output Hash",
    "hashGenerator.copy": "Copy",

    "base64Encoder.title": "Base64 Encoder/Decoder",
    "base64Encoder.inputText": "Input Text",
    "base64Encoder.enterText": "Enter your text here...",
    "base64Encoder.operation": "Operation",
    "base64Encoder.encode": "Encode",
    "base64Encoder.decode": "Decode",
    "base64Encoder.process": "Process",
    "base64Encoder.processing": "Processing...",
    "base64Encoder.output": "Output",
    "base64Encoder.copy": "Copy",

    "jsonFormatter.title": "JSON Formatter",
    "jsonFormatter.inputJson": "Input JSON",
    "jsonFormatter.enterJson": "Enter your JSON here...",
    "jsonFormatter.formatJson": "Format JSON",
    "jsonFormatter.formatting": "Formatting...",
    "jsonFormatter.formattedJson": "Formatted JSON",
    "jsonFormatter.copy": "Copy",
    "jsonFormatter.minify": "Minify",
    "jsonFormatter.validate": "Validate",

    "uuidGenerator.title": "UUID Generator",
    "uuidGenerator.version": "Version",
    "uuidGenerator.count": "Count",
    "uuidGenerator.generateUuid": "Generate UUID",
    "uuidGenerator.generating": "Generating...",
    "uuidGenerator.generatedUuids": "Generated UUIDs",
    "uuidGenerator.copy": "Copy",
    "uuidGenerator.copyAll": "Copy All",

    // Generator Tools
    "passwordGenerator.title": "Password Generator",
    "passwordGenerator.length": "Length",
    "passwordGenerator.includeUppercase": "Include Uppercase",
    "passwordGenerator.includeLowercase": "Include Lowercase",
    "passwordGenerator.includeNumbers": "Include Numbers",
    "passwordGenerator.includeSymbols": "Include Symbols",
    "passwordGenerator.generatePassword": "Generate Password",
    "passwordGenerator.generatedPassword": "Generated Password",
    "passwordGenerator.copy": "Copy",
    "passwordGenerator.strength": "Strength",

    // Converter Tools
    "colorConverter.title": "Color Converter",
    "colorConverter.inputColor": "Input Color",
    "colorConverter.hex": "HEX",
    "colorConverter.rgb": "RGB",
    "colorConverter.hsl": "HSL",
    "colorConverter.convertColor": "Convert Color",
    "colorConverter.converting": "Converting...",
    "colorConverter.colorValues": "Color Values",
    "colorConverter.copy": "Copy",

    // Image Tools
    "imageCompressor.title": "Image Compressor",
    "imageCompressor.uploadImage": "Upload Image",
    "imageCompressor.chooseImage": "Choose Image",
    "imageCompressor.dragDrop": "Drag and drop image here, or click to browse",
    "imageCompressor.quality": "Quality",
    "imageCompressor.compressImage": "Compress Image",
    "imageCompressor.compressing": "Compressing...",
    "imageCompressor.originalSize": "Original Size",
    "imageCompressor.compressedSize": "Compressed Size",
    "imageCompressor.compressionRatio": "Compression Ratio",
    "imageCompressor.download": "Download",

    "backgroundRemover.title": "Background Remover",
    "backgroundRemover.subtitle": "Remove backgrounds from images",
    "backgroundRemover.uploadImage": "Upload Image",
    "backgroundRemover.dropImage": "Drop your image here",
    "backgroundRemover.clickToBrowse": "or click to browse (Max 10MB)",
    "backgroundRemover.removeBackground": "Remove Background",
    "backgroundRemover.removing": "Removing...",
    "backgroundRemover.download": "Download",
    "backgroundRemover.reset": "Reset",

    "imageCropper.title": "Image Cropper",
    "imageCropper.uploadImage": "Upload Image",
    "imageCropper.chooseImage": "Choose Image",
    "imageCropper.dragDrop": "Drag and drop image here, or click to browse",
    "imageCropper.aspectRatio": "Aspect Ratio",
    "imageCropper.free": "Free",
    "imageCropper.square": "Square (1:1)",
    "imageCropper.portrait": "Portrait (3:4)",
    "imageCropper.landscape": "Landscape (4:3)",
    "imageCropper.cropImage": "Crop Image",
    "imageCropper.cropping": "Cropping...",
    "imageCropper.download": "Download",
    "imageCropper.reset": "Reset",

    // Common UI Elements
    "common.upload": "Upload",
    "common.download": "Download",
    "common.copy": "Copy",
    "common.clear": "Clear",
    "common.reset": "Reset",
    "common.generate": "Generate",
    "common.convert": "Convert",
    "common.processing": "Processing...",
    "common.success": "Success!",
    "common.error": "Error",
    "common.warning": "Warning",
    "common.info": "Info",
    "common.close": "Close",
    "common.cancel": "Cancel",
    "common.confirm": "Confirm",
    "common.save": "Save",
    "common.edit": "Edit",
    "common.delete": "Delete",
    "common.add": "Add",
    "common.remove": "Remove",
    "common.update": "Update",
    "common.refresh": "Refresh",
    "common.loading": "Loading...",
    "common.retry": "Retry",
    "common.back": "Back",
    "common.next": "Next",
    "common.previous": "Previous",
    "common.finish": "Finish",
    "common.skip": "Skip"
  },
  es: {
    // Header
    "header.title": "Aptexa ToolHub",
    "header.subtitle": "Herramientas Profesionales en Línea",
    "header.search": "Buscar herramientas...",
    "header.dashboard": "Panel",
    "header.favorites": "Favoritos",
    "header.recent": "Recientes",
    
    // Dashboard
    "dashboard.title": "Herramientas Profesionales en Línea",
    "dashboard.description": "Accede a herramientas poderosas para mejorar tu productividad y optimizar tu flujo de trabajo",
    "dashboard.hero.title": "Herramientas Profesionales en Línea",
    "dashboard.hero.description": "Accede a herramientas poderosas para mejorar tu productividad y optimizar tu flujo de trabajo - desde {barcodes} y {pdfs} hasta {signatures} y utilidades de {development}.",
    "dashboard.hero.barcodes": "generación de códigos de barras",
    "dashboard.hero.pdfs": "procesamiento de PDF",
    "dashboard.hero.signatures": "firmas digitales",
    "dashboard.hero.development": "herramientas de desarrollo",
    "dashboard.stats.tools": "Total de Herramientas",
    "dashboard.stats.categories": "Categorías",
    "dashboard.stats.popular": "Más Popular",
    "dashboard.stats.popularTool": "Herramientas PDF",
    "dashboard.stats.free": "Gratis de Usar",
    "dashboard.quickAccess": "Acceso Rápido",
    "dashboard.allCategories": "Todas las Categorías de Herramientas",
    "dashboard.popularTools": "Herramientas Populares",
    "dashboard.quickActions": "Acciones Rápidas",
    "dashboard.recentlyUsed": "Usadas Recientemente",
    "dashboard.features.title": "¿Por qué elegir ToolHub de Aptexa?",
    "dashboard.features.secure": "Seguro y Privado",
    "dashboard.features.secureDesc": "Todo el procesamiento ocurre en tu navegador. Tus datos nunca salen de tu dispositivo.",
    "dashboard.features.fast": "Súper Rápido",
    "dashboard.features.fastDesc": "Herramientas optimizadas que funcionan instantáneamente sin retrasos del servidor.",
    "dashboard.features.mobile": "Compatible con Móviles",
    "dashboard.features.mobileDesc": "Funciona perfectamente en todos los dispositivos, desde escritorio hasta móvil.",
    
    // Categories
    "category.barcodes.title": "Herramientas de Códigos de Barras y QR",
    "category.barcodes.description": "Generar y escanear varios formatos de códigos de barras",
    "category.pdf-tools.title": "Herramientas PDF",
    "category.pdf-tools.description": "Convertir, fusionar, dividir, comprimir y manipular documentos PDF",
    "category.image-tools.title": "Herramientas de Imagen",
    "category.image-tools.description": "Redimensionar, comprimir, convertir y editar imágenes en varios formatos",
    "category.text-tools.title": "Herramientas de Texto y Contenido",
    "category.text-tools.description": "Formatear, analizar y manipular contenido de texto y código",
    "category.converters.title": "Herramientas de Conversión",
    "category.converters.description": "Convertir unidades, monedas, colores y formatos de archivo",
    "category.generators.title": "Herramientas de Generación",
    "category.generators.description": "Generar contraseñas, firmas, facturas y gradientes CSS",
    "category.developer-tools.title": "Herramientas de Desarrollador",
    "category.developer-tools.description": "Depurar, probar y optimizar código con utilidades profesionales para desarrolladores",
    
    // Barcode Generator
    "barcodeGenerator.title": "Generador de Códigos de Barras y QR",
    "barcodeGenerator.subtitle": "Genere más de 85 tipos de códigos de barras incluyendo códigos QR, códigos de barras lineales, códigos postales, tarjetas de negocio, Wi-Fi, eventos y formatos especializados",
    "barcodeGenerator.barcodeType": "Tipo de Código de Barras",
    "barcodeGenerator.available": "disponible",
    "barcodeGenerator.searchTypes": "Buscar tipos de códigos de barras...",
    "barcodeGenerator.allCategories": "Todas las Categorías",
    "barcodeGenerator.selectType": "Seleccione un tipo de código de barras...",
    "barcodeGenerator.noTypesFound": "No se encontraron tipos de códigos de barras que coincidan con su búsqueda",
    "barcodeGenerator.professional": "Profesional",
    "barcodeGenerator.dataToEncode": "Datos a Codificar",
    "barcodeGenerator.useSampleData": "Usar Datos de Muestra",
    "barcodeGenerator.scaleLabel": "Escala",
    "barcodeGenerator.heightLabel": "Altura",
    "barcodeGenerator.includeText": "Incluir Texto",
    "barcodeGenerator.textSize": "Tamaño del Texto",
    "barcodeGenerator.backgroundColor": "Color de Fondo",
    "barcodeGenerator.generate": "Generar Código de Barras",
    "barcodeGenerator.generating": "Generando...",
    "barcodeGenerator.generatedBarcode": "Código de Barras Generado",
    "barcodeGenerator.copy": "Copiar",
    "barcodeGenerator.barcodeWillAppear": "Su código de barras aparecerá aquí",
    "barcodeGenerator.professionalGrade": "Grado Profesional",
    "barcodeGenerator.enterData": "Ingrese sus datos aquí...",
    "barcodeGenerator.sampleDataLoaded": "Datos de Muestra Cargados",
    "barcodeGenerator.sampleDataDesc": "Se han cargado datos de muestra para este tipo de código de barras",
    "barcodeGenerator.barcodeGenerated": "Código de Barras Generado",
    "barcodeGenerator.barcodeGeneratedDesc": "¡Su código de barras auténtico y escaneable ha sido generado!",
    "barcodeGenerator.generationFailed": "Error en la Generación",
    "barcodeGenerator.invalidInput": "Entrada Inválida",
    "barcodeGenerator.selectTypeAndEnter": "Por favor seleccione un tipo de código de barras e ingrese datos",
    "barcodeGenerator.copiedClipboard": "Copiado al Portapapeles",
    "barcodeGenerator.copiedClipboardDesc": "Imagen del código de barras copiada al portapapeles",
    "barcodeGenerator.copyFailed": "Error al Copiar",
    "barcodeGenerator.copyFailedDesc": "No se pudo copiar al portapapeles",
    "barcodeGenerator.svgFeature": "Función SVG",
    "barcodeGenerator.svgFeatureDesc": "La descarga SVG se implementará en la próxima actualización. La descarga PNG está completamente funcional.",

    // Barcode Categories
    "barcode.linearCodes": "Códigos Lineales",
    "barcode.postalCodes": "Códigos Postales", 
    "barcode.gs1DataBar": "GS1 DataBar",
    "barcode.eanUpc": "EAN / UPC",
    "barcode.twoDCodes": "Códigos 2D",
    "barcode.gs1TwoDCodes": "Códigos GS1 2D",
    "barcode.bankingPayment": "Banca y Pagos",
    "barcode.mobileTags": "Etiquetas Móviles",
    "barcode.healthcare": "Códigos de Salud",
    "barcode.businessCards": "Tarjetas de Negocio",
    "barcode.events": "Códigos de Eventos",
    "barcode.wifi": "Códigos Wi-Fi",
    "barcode.isbn": "Códigos ISBN",

    // Barcode Type Names
    "Code-128": "Código-128",
    "Code-11": "Código-11",
    "Code 2 of 5": "Código 2 de 5",
    "Code-39": "Código-39",
    "Code-39 Full ASCII": "Código-39 ASCII Completo",
    "Code-93": "Código-93",
    "GS1-128": "GS1-128",
    "MSI": "MSI",
    "Pharmacode": "Código Farmacéutico",
    "Pharmacode Two-Track": "Código Farmacéutico Dos Pistas",
    "Telepen": "Telepen",
    "Australian Post": "Correo Australiano",
    "Deutsche Post Identcode": "Código Identidad Correo Alemán",
    "DPD Code": "Código DPD",
    "Japan Post": "Correo Japonés",
    "Royal Mail 4-State": "Correo Real 4-Estados",
    "USPS POSTNET": "USPS POSTNET",
    "USPS Intelligent Mail": "USPS Correo Inteligente",
    "GS1 DataBar Omnidirectional": "GS1 DataBar Omnidireccional",
    "GS1 DataBar Stacked": "GS1 DataBar Apilado",
    "GS1 DataBar Limited": "GS1 DataBar Limitado",
    "GS1 DataBar Expanded": "GS1 DataBar Expandido",
    "GS1 DataBar Expanded Stacked": "GS1 DataBar Expandido Apilado",
    "EAN-8": "EAN-8",
    "EAN-13": "EAN-13",
    "UPC-A": "UPC-A",
    "UPC-E": "UPC-E",
    "Data Matrix": "Matriz de Datos",
    "QR Code": "Código QR",
    "PDF417": "PDF417",
    "MicroPDF417": "MicroPDF417",
    "Aztec Code": "Código Azteca",
    "MaxiCode": "MaxiCódigo",

    // Currency Converter
    "currencyConverter.title": "Conversor de Monedas en Tiempo Real",
    "currencyConverter.lastUpdated": "Última Actualización",
    "currencyConverter.refresh": "Actualizar",
    "currencyConverter.from": "De",
    "currencyConverter.to": "A",
    "currencyConverter.enterAmount": "Ingrese cantidad",
    "currencyConverter.convertedAmount": "Cantidad Convertida",
    "currencyConverter.convertCurrency": "Convertir Moneda",
    "currencyConverter.converting": "Convirtiendo...",
    "currencyConverter.clear": "Limpiar",
    "currencyConverter.liveExchangeRates": "Tasas de Cambio en Vivo",
    "currencyConverter.autoRefresh": "Actualización Automática",
    "currencyConverter.realTimeData": "Datos de moneda en tiempo real actualizados cada hora desde mercados financieros",
    "currencyConverter.intelligentCaching": "Tasas que se actualizan automáticamente con caché inteligente",

    // Common UI Elements
    "common.upload": "Subir",
    "common.download": "Descargar",
    "common.copy": "Copiar",
    "common.clear": "Limpiar",
    "common.reset": "Restablecer",
    "common.generate": "Generar",
    "common.convert": "Convertir",
    "common.processing": "Procesando...",
    "common.success": "¡Éxito!",
    "common.error": "Error",
    "common.warning": "Advertencia",
    "common.info": "Información",
    "common.close": "Cerrar",
    "common.cancel": "Cancelar",
    "common.confirm": "Confirmar",
    "common.save": "Guardar",
    "common.edit": "Editar",
    "common.delete": "Eliminar",
    "common.add": "Agregar",
    "common.remove": "Quitar",
    "common.update": "Actualizar",
    "common.refresh": "Actualizar",
    "common.loading": "Cargando...",
    "common.retry": "Reintentar",
    "common.back": "Atrás",
    "common.next": "Siguiente",
    "common.previous": "Anterior",
    "common.finish": "Finalizar",
    "common.skip": "Omitir"
  },
  ar: {
    // Header
    "header.title": "Aptexa ToolHub",
    "header.subtitle": "أدوات احترافية على الإنترنت",
    "header.search": "البحث في الأدوات...",
    "header.dashboard": "لوحة التحكم",
    "header.favorites": "المفضلة",
    "header.recent": "الحديثة",
    
    // Dashboard
    "dashboard.title": "أدوات احترافية على الإنترنت",
    "dashboard.description": "احصل على أدوات قوية لتعزيز إنتاجيتك وتحسين سير عملك",
    "dashboard.hero.title": "أدوات احترافية على الإنترنت",
    "dashboard.hero.description": "احصل على أدوات قوية لتعزيز إنتاجيتك وتحسين سير عملك - من {barcodes} و{pdfs} إلى {signatures} وأدوات {development}.",
    "dashboard.hero.barcodes": "توليد الباركود",
    "dashboard.hero.pdfs": "معالجة PDF",
    "dashboard.hero.signatures": "التوقيعات الرقمية",
    "dashboard.hero.development": "أدوات التطوير",
    "dashboard.stats.tools": "إجمالي الأدوات",
    "dashboard.stats.categories": "الفئات",
    "dashboard.stats.popular": "الأكثر شعبية",
    "dashboard.stats.popularTool": "أدوات PDF",
    "dashboard.stats.free": "مجاني للاستخدام",
    "dashboard.quickAccess": "الوصول السريع",
    "dashboard.allCategories": "جميع فئات الأدوات",
    "dashboard.popularTools": "الأدوات الشائعة",
    "dashboard.quickActions": "الإجراءات السريعة",
    "dashboard.recentlyUsed": "المستخدمة مؤخراً",
    "dashboard.features.title": "لماذا تختار Aptexa's ToolHub؟",
    "dashboard.features.secure": "آمن وخاص",
    "dashboard.features.secureDesc": "تتم جميع العمليات في متصفحك. بياناتك لا تغادر جهازك أبداً.",
    "dashboard.features.fast": "سريع جداً",
    "dashboard.features.fastDesc": "أدوات محسنة تعمل فوراً بدون تأخير من الخادم.",
    "dashboard.features.mobile": "متوافق مع الجوال",
    "dashboard.features.mobileDesc": "يعمل بشكل مثالي على جميع الأجهزة، من سطح المكتب إلى الجوال.",
    
    // Categories
    "category.barcodes.title": "أدوات الباركود و QR",
    "category.barcodes.description": "إنشاء ومسح تنسيقات مختلفة من الباركود",
    "category.pdf-tools.title": "أدوات PDF",
    "category.pdf-tools.description": "تحويل ودمج وتقسيم وضغط ومعالجة مستندات PDF",
    "category.image-tools.title": "أدوات الصور",
    "category.image-tools.description": "تغيير الحجم والضغط والتحويل وتحرير الصور بتنسيقات مختلفة",
    "category.text-tools.title": "أدوات النص والمحتوى",
    "category.text-tools.description": "تنسيق وتحليل ومعالجة محتوى النص والكود",
    "category.converters.title": "أدوات التحويل",
    "category.converters.description": "تحويل الوحدات والعملات والألوان وتنسيقات الملفات",
    "category.generators.title": "أدوات الإنشاء",
    "category.generators.description": "إنشاء كلمات المرور والتوقيعات والفواتير وتدرجات CSS",
    "category.developer-tools.title": "أدوات المطورين",
    "category.developer-tools.description": "تصحيح واختبار وتحسين الكود بأدوات مطورين احترافية",
    
    // Barcode Generator
    "barcodeGenerator.title": "مولد الباركود ورمز الاستجابة السريعة",
    "barcodeGenerator.subtitle": "توليد أكثر من 85 نوعاً من الباركود بما في ذلك أكواد QR والباركود الخطي والرموز البريدية وبطاقات الأعمال وWi-Fi والأحداث والتنسيقات المتخصصة",
    "barcodeGenerator.barcodeType": "نوع الباركود",
    "barcodeGenerator.available": "متاح",
    "barcodeGenerator.searchTypes": "البحث في أنواع الباركود...",
    "barcodeGenerator.allCategories": "جميع الفئات",
    "barcodeGenerator.selectType": "اختر نوع الباركود...",
    "barcodeGenerator.noTypesFound": "لم يتم العثور على أنواع باركود تطابق بحثك",
    "barcodeGenerator.professional": "احترافي",
    "barcodeGenerator.dataToEncode": "البيانات المراد تشفيرها",
    "barcodeGenerator.useSampleData": "استخدام بيانات العينة",
    "barcodeGenerator.scaleLabel": "المقياس",
    "barcodeGenerator.heightLabel": "الارتفاع",
    "barcodeGenerator.includeText": "تضمين النص",
    "barcodeGenerator.textSize": "حجم النص",
    "barcodeGenerator.backgroundColor": "لون الخلفية",
    "barcodeGenerator.generate": "توليد الباركود",
    "barcodeGenerator.generating": "جارٍ التوليد...",
    "barcodeGenerator.generatedBarcode": "الباركود المُولد",
    "barcodeGenerator.copy": "نسخ",
    "barcodeGenerator.barcodeWillAppear": "سيظهر الباركود الخاص بك هنا",
    "barcodeGenerator.professionalGrade": "درجة احترافية",
    "barcodeGenerator.enterData": "أدخل بياناتك هنا...",
    "barcodeGenerator.sampleDataLoaded": "تم تحميل بيانات العينة",
    "barcodeGenerator.sampleDataDesc": "تم تحميل بيانات العينة لهذا النوع من الباركود",
    "barcodeGenerator.barcodeGenerated": "تم توليد الباركود",
    "barcodeGenerator.barcodeGeneratedDesc": "تم توليد الباركود الأصلي القابل للمسح بنجاح!",
    "barcodeGenerator.generationFailed": "فشل في التوليد",
    "barcodeGenerator.invalidInput": "إدخال غير صالح",
    "barcodeGenerator.selectTypeAndEnter": "يرجى اختيار نوع الباركود وإدخال البيانات",
    "barcodeGenerator.copiedClipboard": "تم النسخ إلى الحافظة",
    "barcodeGenerator.copiedClipboardDesc": "تم نسخ صورة الباركود إلى الحافظة",
    "barcodeGenerator.copyFailed": "فشل النسخ",
    "barcodeGenerator.copyFailedDesc": "تعذر النسخ إلى الحافظة",
    "barcodeGenerator.svgFeature": "ميزة SVG",
    "barcodeGenerator.svgFeatureDesc": "سيتم تنفيذ تحميل SVG في التحديث القادم. تحميل PNG يعمل بشكل كامل.",

    // Currency Converter
    "currencyConverter.title": "محول العملات في الوقت الفعلي",
    "currencyConverter.lastUpdated": "آخر تحديث",
    "currencyConverter.refresh": "تحديث",
    "currencyConverter.from": "من",
    "currencyConverter.to": "إلى",
    "currencyConverter.enterAmount": "أدخل المبلغ",
    "currencyConverter.convertedAmount": "المبلغ المحول",
    "currencyConverter.convertCurrency": "تحويل العملة",
    "currencyConverter.converting": "جارٍ التحويل...",
    "currencyConverter.clear": "مسح",
    "currencyConverter.liveExchangeRates": "أسعار الصرف المباشرة",
    "currencyConverter.autoRefresh": "التحديث التلقائي",
    "currencyConverter.realTimeData": "بيانات العملة في الوقت الفعلي يتم تحديثها كل ساعة من الأسواق المالية",
    "currencyConverter.intelligentCaching": "تحديث الأسعار تلقائياً مع نظام تخزين مؤقت ذكي",

    // Barcode Categories
    "barcode.linearCodes": "الرموز الخطية",
    "barcode.postalCodes": "الرموز البريدية", 
    "barcode.gs1DataBar": "GS1 DataBar",
    "barcode.eanUpc": "EAN / UPC",
    "barcode.twoDCodes": "الرموز ثنائية الأبعاد",
    "barcode.gs1TwoDCodes": "رموز GS1 ثنائية الأبعاد",
    "barcode.bankingPayment": "البنوك والمدفوعات",
    "barcode.mobileTags": "علامات الجوال",
    "barcode.healthcare": "رموز الرعاية الصحية",
    "barcode.businessCards": "بطاقات الأعمال",
    "barcode.events": "رموز الأحداث",
    "barcode.wifi": "رموز Wi-Fi",
    "barcode.isbn": "رموز ISBN",

    // Barcode Type Names
    "Code-128": "كود-128",
    "Code-11": "كود-11",
    "Code 2 of 5": "كود 2 من 5",
    "Code-39": "كود-39",
    "Code-39 Full ASCII": "كود-39 ASCII كامل",
    "Code-93": "كود-93",
    "GS1-128": "GS1-128",
    "MSI": "MSI",
    "Pharmacode": "فارماكود",
    "Pharmacode Two-Track": "فارماكود مسارين",
    "Telepen": "تيليبين",
    "Australian Post": "البريد الأسترالي",
    "Deutsche Post Identcode": "كود هوية البريد الألماني",
    "DPD Code": "كود DPD",
    "Japan Post": "البريد الياباني",
    "Royal Mail 4-State": "البريد الملكي 4-حالات",
    "USPS POSTNET": "USPS POSTNET",
    "USPS Intelligent Mail": "USPS البريد الذكي",
    "GS1 DataBar Omnidirectional": "GS1 DataBar متعدد الاتجاهات",
    "GS1 DataBar Stacked": "GS1 DataBar مكدس",
    "GS1 DataBar Limited": "GS1 DataBar محدود",
    "GS1 DataBar Expanded": "GS1 DataBar موسع",
    "GS1 DataBar Expanded Stacked": "GS1 DataBar موسع مكدس",
    "EAN-8": "EAN-8",
    "EAN-13": "EAN-13",
    "UPC-A": "UPC-A",
    "UPC-E": "UPC-E",
    "Data Matrix": "مصفوفة البيانات",
    "QR Code": "رمز الاستجابة السريعة",
    "PDF417": "PDF417",
    "MicroPDF417": "MicroPDF417",
    "Aztec Code": "كود الأزتك",
    "MaxiCode": "ماكسي كود",

    // Common UI Elements
    "common.upload": "رفع",
    "common.download": "تحميل",
    "common.copy": "نسخ",
    "common.clear": "مسح",
    "common.reset": "إعادة تعيين",
    "common.generate": "إنشاء",
    "common.convert": "تحويل",
    "common.processing": "جارٍ المعالجة...",
    "common.success": "نجح!",
    "common.error": "خطأ",
    "common.warning": "تحذير",
    "common.info": "معلومات",
    "common.close": "إغلاق",
    "common.cancel": "إلغاء",
    "common.confirm": "تأكيد",
    "common.save": "حفظ",
    "common.edit": "تحرير",
    "common.delete": "حذف",
    "common.add": "إضافة",
    "common.remove": "إزالة",
    "common.update": "تحديث",
    "common.refresh": "تحديث",
    "common.loading": "جارٍ التحميل...",
    "common.retry": "إعادة المحاولة",
    "common.back": "رجوع",
    "common.next": "التالي",
    "common.previous": "السابق",
    "common.finish": "إنهاء",
    "common.skip": "تخطي"
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguage] = useState<Language>("en");

  const handleSetLanguage = (lang: Language) => {
    setLanguage(lang);
    localStorage.setItem("language", lang);
    
    // Apply RTL direction for Arabic
    if (lang === "ar") {
      document.documentElement.dir = "rtl";
      document.documentElement.lang = "ar";
    } else {
      document.documentElement.dir = "ltr";
      document.documentElement.lang = lang;
    }
  };

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  // Initialize language from localStorage on mount
  useEffect(() => {
    const savedLanguage = localStorage.getItem("language") as Language;
    if (savedLanguage && ["en", "es", "ar"].includes(savedLanguage)) {
      handleSetLanguage(savedLanguage);
    }
  }, []);

  return (
    <LanguageContext.Provider value={{ language, setLanguage: handleSetLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
}